#!/bin/bash

# Source: https://www.linuxfromscratch.org/lfs/view/stable-systemd
# Author: Wasym Atieh Alonso

############################
# Script Environment Setup #
############################
source chapters/envsetup.sh

####################################
# CHAPTER 03: Packages and Patches #
####################################
confirm
source chapters/chapter03.sh

##################################
# CHAPTER 04: Final Preparations #
##################################
confirm
source chapters/chapter04.sh

###########################################
# CHAPTER 05: Compiling a Cross-Toolchain #
###########################################
confirm
source chapters/chapter05.sh

# Recover cursor
tput cnorm; exit 0