#!/bin/bash

# Source: https://www.linuxfromscratch.org/lfs/view/stable-systemd
# Author: Wasym Atieh Alonso

############################
# Script Environment Setup #
############################
source chapters/envsetup.sh

####################################
# CHAPTER 03: Packages and Patches #
####################################
confirm
source chapters/chapter03.sh

##################################
# CHAPTER 04: Final Preparations #
##################################
confirm
source chapters/chapter04.sh

###########################################
# CHAPTER 05: Compiling a Cross-Toolchain #
###########################################
confirm
source chapters/chapter05.sh

###############################################
# CHAPTER 06: Cross Compiling Temporary Tools #
###############################################
confirm
source chapters/chapter06.sh

#######################################################################
# CHAPTER 07: Entering Chroot and Building Additional Temporary Tools #
#######################################################################
confirm
source chapters/chapter07.sh

################################################
# CHAPTER 08: Installing Basic System Software #
################################################
confirm
source chapters/chapter08.sh

####################################
# CHAPTER 09: System Configuration #
####################################
confirm
source chapters/chapter09.sh

##############################################
# CHAPTER 10: Making the LFS System Bootable #
##############################################
confirm
source chapters/chapter10.sh

# Recover cursor
tput cnorm; exit 0